### ISSUE TITLE
Stateless component

### ISSUE THREAD

**Issue by garbin** [selvagsz/react-async-button#36]
I use redux, All state are in store, so could you add stateless support? add a prop `state` for rendering?

**Comment by selvagsz** [comment]
@garbin I don't understand the need to pass the state inside the component. I too use redux for state management. The `onClick` handler should return a promise for the pending state of the button

**Comment by selvagsz** [comment]
I don't think this is an issue with the component. Closing this for now. Feel free to reopen, if you can demonstrate the issue with an example.
